### ISSUE TITLE
Header soup

### ISSUE THREAD

**Issue by cup** [tfc/pprintpp#7]
Other projects include system headers as needed, as well as setting locale as
needed, leading to clean code:

~~~c
#include <fmt/format.h>
int main() {
   fmt::print("{:n}\n", 1000);
}
~~~

pprintpp does not include system headers as needed, and does not set locale as
needed, leading to verbose code:

~~~c
#include "pprintpp.hpp"
#include <clocale>
#include <cstdio>
int main() {
   setlocale(LC_ALL, "");
   pprintf("{'}\n", 1000);
}
~~~

**Comment by cup** [comment]
https://github.com/tfc/pprintpp/issues/6

**Comment by tfc** [comment]
`pprintpp` is a frontend to `printf` with the sole purpose of setting up types at compile time automatically for you. If this library did other things than that, it would not be `printf`-agnostic any longer.

In order to get something that works like your lib `fmt` example, one would bundle up a specific printf implementation with `pprintpp` and provide it as another library.

The projects (microkernel operating system/virtualization kernel/userspace) in which `pprintpp` is used are set up just like you suggested.

**Comment by tfc** [comment]
@cup you did not really ask a question and the issue that `pprintpp` does not setup system headers as needed looks like a "wontfix" to me because `pprintpp` is not designed to assume availability of the system headers that you suggest.

Can we close this item or do you have further input on this?

**Comment by tfc** [comment]
Hey there, i am closing this due to lacking input. Feel free to reopen.
